### ISSUE TITLE
0.2.2 not installing 

### ISSUE THREAD

**Issue by nobody5050** [dahlia-os/UI-Apk#10]
Apk version 0.2.2 doesnt wanr to play well with lollipop. output is: "app not installed"

**Comment by EnderNightLord-ChromeBook** [comment]
I just installed it...

**Comment by EnderNightLord-ChromeBook** [comment]
![image](https://user-images.githubusercontent.com/31677287/61164774-6a4d1b80-a56c-11e9-80fd-d937452812a9.png)

**Comment by nobody5050** [comment]
but.. its not working :(

**Comment by nobody5050** [comment]
@EnderNightLord-ChromeBook what api level is it work on?

**Comment by EnderNightLord-ChromeBook** [comment]
I dunno... but I know it works on android 9 pie and android oreo.
